server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: xy-provider
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848


feign:
  hystrix:
    enabled: true

xy:
  test:
    name : xy-myself
  ip:
    list: 192.168.4.38,192.168.4.37,127.0.0.1

#springfox:
#  documentation:
#    enabled: true